#!/bin/bash

#SBATCH -J test              # Job Name
#SBATCH -N 1                 # Number of nodes (24 cores/node)
#SBATCH -t 00:10:00          # Run time (hh:mm:ss) - 24 hours
#SBATCH -p debug             # Queue name "normal"
#SBATCH -e dam.err           # Name of the output file (eg. myMPI.oJobID)
#SBATCH -o dam.out           # Name of the output file (eg. myMPI.oJobID)
#SBATCH --mail-type ALL      # Opt in for email notifications
#SBATCH --mail-user njeevanjee@lbl.gov  # User receiving emails 

# Set the run path
path=test

# Installation configuration
damname=dam
damdir=${HOME}/edison/rad_cooling/dam
nprocs=$(squeue -o "%C")
run="srun -n 4 $damdir/$damname $path > $path/log"

# Check that the path is of correct form
if [ ! -d $damdir/$path ]
then
   echo "Error in resub: The directory $damdir/$path does not exist"
   exit 1
fi

# Make directories
mkdir -p $damdir/$path/data

# Run DAM
cd $damdir
eval $run
