#!/bin/bash
#PBS -N test               # Job Name
#PBS -l nodes=1            # Number of tasks (cores)
#PBS -l walltime=16:00:00  # Run time (hh:mm:ss) - 16 hours
#PBS -l partition=c4
#PBS -A gfdl_m             # Account
#PBS -q batch              # Queue name
#PBS -e dam.err            # Name of the output file (eg. myMPI.oJobID)
#PBS -o dam.out            # Name of the output file (eg. myMPI.oJobID)
#PBS -m abe

# Set the case/path
path=test

# Installation configuration
CPERM=/lustre/f1/unswept
project=agg_co2
projectdir=$CPERM/$USER/$project 
run="aprun -n 36 $projectdir/dam $path > $path/log"

# Check that the path is of correct form
if [ ! -d $projectdir/$path ]
then
   echo "Error in resub: The directory $projectdir/$path does not exist"
   exit 1
fi

# Make directories
mkdir -p $projectdir/$path/data

# Run DAM
cd $projectdir
eval $run
